# Generated by Django 5.1.4 on 2024-12-30 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(120),
                    django.core.validators.MinValueValidator(0),
                ]
            ),
        ),
    ]
