# Generated by Django 5.1.4 on 2024-12-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_bulkuploadlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkuploadlogs',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
