version: '3.12'

volumes:
  postgres_data:

services:
  celery: &celery
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    volumes:
      - .:/app/
      - type: bind
        source: .
        target: /app
    command: watchfiles --filter python celery.__main__.main --args '-A config worker -l INFO'

  server:
    <<: *celery
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000

  redis:
    image: redis:6
    ports:
      - 6379:6379

  
